name = "JLD2Blosc"
uuid = "7f28b69e-c83f-4960-977f-81f66861f7ce"
authors = ["Jonas Isensee <jonas.isensee@web.de>"]
version = "0.1.0"

[deps]
ChunkCodecLibBlosc = "c6a955be-ab7f-4fbb-b38f-caf93db6b928"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
ChunkCodecLibBlosc = "0.2.0"
JLD2 = "0.5.15"
