branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
  - linux
  - osx

julia:
  - "1.0"
  - "1.3"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  email: false

# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("JLD2"); Pkg.test("JLD2"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("JLD2")); Pkg.add("Coverage"); Pkg.checkout("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
