name = "JLD2Lz4"
uuid = "49ca2578-dfa4-4b24-b5ab-b610893dc52a"
authors = ["Jonas Isensee <jonas.isensee@web.de>"]
version = "0.1.0"

[deps]
ChunkCodecLibLz4 = "7e9cc85e-5614-42a3-ad86-b78f920b38a5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
ChunkCodecLibLz4 = "0.2.2, 0.3"
JLD2 = "0.6"
julia = "1.9"
